# Generated by Django 2.2.7 on 2019-11-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_menuimage_menuitem_menurating_menureviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('Appetizers', 'Appetizers'), ('Entree', 'Entree'), ('Dessert', 'Dessert'), ('Drinks - Non Alcoholic', 'Drinks - Non Alcoholic'), ('Drinks - Alcoholic', 'Drinks - Alcoholic')], default='Appetizers', max_length=21),
        ),
    ]
